version: '3'

services:
  database:
    container_name: database_mysql
    image: mysql:8.0.22
    restart: always
    
    command: [
        '--default-authentication-plugin=mysql_native_password'
        ]
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: pdv
      MYSQL_USER: pdv
      MYSQL_PASSWORD: pdv123456
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql
    deploy:
      resources:
        limits:
          memory: 512M

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    restart: always
    environment:
      PMA_HOST: database_mysql
      PMA_USER: root
      PMA_PASSWORD: 123456
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - 8080:80
    depends_on:
      - database
    volumes:
      - /sessions
    deploy:
      resources:
        limits:
          memory: 512M



volumes:
  mysql_data:



networks:
  default:
